# Custom Language File for Launcher Customizer

[ejs.app]
title = "VOGO Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/GaelHF/VOGOLauncher"
mediaTwitterURL = "https://x.com/VOGONetwork"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/B8EXHdRGtK"

[ejs.settings]
sourceGithubLink = "https://github.com/GaelHF/VOGOLauncher"
supportLink = "https://github.com/GaelHF/VOGOLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO THE VOGO LAUNCHER"
welcomeDescription = "A Simple Way To Play VOGO Minecraft Moddeds Servers"
welcomeDescCTA = "You are just a few clicks away from it."
