# Custom Language File for Launcher Customizer

[ejs.app]
title = "VOGO Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/GaelHF/VOGO-Launcher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/GaelHF/VOGO-Launcher"
supportLink = "https://github.com/GaelHF/VOGO-Launcher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO THE VOGO LAUNCHER"
welcomeDescription = "A Simple Way To Play VOGO Minecraft Moddeds Servers"
welcomeDescCTA = "You are just a few clicks away from it."
